sf:
  password: "![BCzaw2k9PrHaPEaGiGEKGA==]"
  token: "![Hx3nAIjW/OungUI21c1KiwRV0XGbRMB9fhqFLPLiA4A=]"
  username: "![XwfxabEk2KaIiy4pbqabD3F8eQx95wLblqSccv3mi7DhsOjLZpCBjw==]"

ad:
  id: "![CNzTmqaHE2CRF8D+FT8ESA==]"